name: Metrics
on:
  # 每天午夜触发
  schedule: [{ cron: "0 0 * * *" }]
  # 手动触发工作流
  workflow_dispatch:
  # 在 master 或 main 分支推送时触发
  push:
    branches: ["master", "main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # 启用语言插件
          plugin_languages: yes
          # 启用深度分析模式
          plugin_languages_indepth: yes
          # 显示代码行数和字节大小
          plugin_languages_details: lines, bytes-size
